### ISSUE TITLE
Attach top-most PART to ROOT if it does not exist in DB yet

### ISSUE THREAD

**Issue by valdasraps** [valdasraps/cmsdbldr#2]
In case parts XML is submitted to loader and top-most PART is still not in the database than create it and attach to ROOT.

**Comment by valdasraps** [comment]
Example xml:

`<?xml version="1.0"?>
<ROOT>
  <PARTS>
    <PART>
      <SERIAL_NUMBER>GE1/1-X-S-CERN-0001</SERIAL_NUMBER>
      <NAME_LABEL>GE1/1-X-S-CERN-0001</NAME_LABEL>
      <LOCATION>904</LOCATION>
      <COMMENT_DESCRIPTION></COMMENT_DESCRIPTION>
      <BARCODE>1111</BARCODE>
      <KIND_OF_PART>GEM Chamber</KIND_OF_PART>
      <CHILDREN>
        <PART>
          <SERIAL_NUMBER>PCB-VIII-RO-S-0004</SERIAL_NUMBER>
          <KIND_OF_PART>GEM Readout PCB</KIND_OF_PART>
        </PART>
        <PART>
          <SERIAL_NUMBER>PCB-VIII-DR-S-0005</SERIAL_NUMBER>
          <KIND_OF_PART>GEM Drift PCB</KIND_OF_PART>
        </PART>
        <PART>
          <SERIAL_NUMBER>FOIL-B13-S-0140</SERIAL_NUMBER>
          <KIND_OF_PART>GEM Foil</KIND_OF_PART>
          <PREDEFINED_ATTRIBUTES>
            <ATTRIBUTE>
              <NAME>Foil Position</NAME>
              <VALUE>GEM1</VALUE>
            </ATTRIBUTE>
          </PREDEFINED_ATTRIBUTES>
        </PART>
        <PART>
          <SERIAL_NUMBER>FOIL-B13-S-0138</SERIAL_NUMBER>
          <KIND_OF_PART>GEM Foil</KIND_OF_PART>
          <PREDEFINED_ATTRIBUTES>
            <ATTRIBUTE>
              <NAME>Foil Position</NAME>
              <VALUE>GEM2</VALUE>
            </ATTRIBUTE>
          </PREDEFINED_ATTRIBUTES>
        </PART>
        <PART>
          <SERIAL_NUMBER>FOIL-B13-S-0147</SERIAL_NUMBER>
          <KIND_OF_PART>GEM Foil</KIND_OF_PART>
          <PREDEFINED_ATTRIBUTES>
            <ATTRIBUTE>
              <NAME>Foil Position</NAME>
              <VALUE>GEM3</VALUE>
            </ATTRIBUTE>
          </PREDEFINED_ATTRIBUTES>
        </PART>
      </CHILDREN>
    </PART>
  </PARTS>
</ROOT>`

**Comment by Aivaro** [comment]
DB Loader looks up parts in DB by (in priority): ID, BARCODE, KIND_OF_PART + NAME, KIND_OF_PART + SERIAL_NUMBER. If part is found on any of these steps the consistency of other information is not beeing checked. I.e. if BARCODE - found, then KIND_OF_PART is not checked at all. In this example XML BARCODE 1111 already exists for different kind of part so DB Loader considers that the PART is there. No actions needed.

**Comment by valdasraps** [comment]
Works as expected
